"""
Structural contract exposed by platform mouse hook implementations.
"""

from typing import Any, Callable, Protocol, runtime_checkable

from core.mouse_hook_types import HidRuntimeState


@runtime_checkable
class MouseHookLike(Protocol):
    debug_mode: bool
    invert_vscroll: bool
    invert_hscroll: bool
    divert_mode_shift: bool
    divert_dpi_switch: bool
    # When True, the connected Logitech device is performing scroll
    # inversion at the firmware level (HID++ 0x2121 / 0x2150). The OS-layer
    # inversion path must be skipped to avoid double flipping.
    wheel_native_invert_active: bool
    _hid_gesture: Any

    def register(self, event_type: str, callback: Callable[[Any], None]) -> None: ...
    def block(self, event_type: str) -> None: ...
    def unblock(self, event_type: str) -> None: ...
    def reset_bindings(self) -> None: ...
    def configure_gestures(
        self,
        enabled: bool = False,
        threshold: int = 50,
        commit_window_ms: int = 400,
        settle_ms: int = 90,
        cross_ratio: float = 0.5,
    ) -> None: ...
    def set_connection_change_callback(self, cb: Callable[[bool], None]) -> None: ...
    def set_debug_callback(self, callback: Callable[[str], None]) -> None: ...
    def set_gesture_callback(self, callback: Callable[[Any], None]) -> None: ...
    def start_raw_hid_learning(self, duration_s: int = 60) -> bool: ...
    @property
    def device_connected(self) -> bool: ...
    @property
    def connected_device(self) -> Any: ...
    @property
    def hid_runtime_state(self) -> HidRuntimeState: ...
    def dump_device_info(self) -> Any: ...
    def start(self) -> bool: ...
    def stop(self) -> None: ...
